/-
Copyright (c) 2026 Jovan Gerbscheid. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jovan Gerbscheid
-/

module
public import Mathlib.Tactic.ApplyFun

set_option linter.style.header false
set_option linter.directoryDependency false

/-! # Diamonds in instances
This linter reports diamonds in instances
-/

public meta section

open Lean Meta

/-- Given an instance `inst`, return all data projection instances (e.g. `inst.toAddMonoid`). -/
partial def getStructureDataProjections (e : Expr) (acc : Array Expr := #[]) :
    StateRefT NameSet MetaM (Array Expr) := do
  let eType ← whnf (← inferType e)
  if ← isProp eType then return acc
  let .const structName us := eType.getForallBody.getAppFn
    | throwError "{e} is not an instance of a structure"
  unless isClass (← getEnv) structName do return acc
  if (← get).contains structName then return acc
  modify (·.insert structName)
  let some info := getStructureInfo? (← getEnv) structName | return acc
  info.parentInfo.foldlM (init := acc.push e) fun acc info ↦ do
    if ← isInstance info.projFn then
      let proj := Expr.app (mkAppN (.const info.projFn us) eType.getAppArgs) e
      getStructureDataProjections proj acc
    else
      return acc

/-- Compare the given instance with the one generated by type class synthesis. -/
def compareWithSynthesized (e : Expr) : MetaM (Option MessageData) := do
  let type ← inferType e
  let .some inst ← trySynthInstance type | return none
  if ← withReducibleAndInstances <| isDefEq e inst then
    return none
  if ← withDefault <| isDefEq e inst then
    return m!"Projection {indentExpr e} : {← inferType e}\nis not defeq to the \
      synthesized instance {indentExpr inst}"
  else
    return none

def findDiamonds (declName : Name) : MetaM (Option MessageData) := withReducible do
  unless ← isInstance declName do return none
  let cinfo ← getConstInfo declName
  let constants := Expr.getUsedConstants cinfo.type
  if constants.any (· matches `Additive | `Multiplicative |
      `Lex | `Colex | `DomAddAct | `DomMulAct | `MulOpposite | `AddOpposite
      | `RestrictScalars | `WithVal) then
    return none
  forallTelescopeReducing (whnfType := true) cinfo.type fun xs _ ↦ do
    let inst := mkAppN (.const declName (cinfo.levelParams.map .param)) xs
    let mut firstMsg : Option MessageData := none
    let mut later : Array Expr := #[]
    logInfo "fjiosd"
    for proj in ← (getStructureDataProjections inst).run' {} do
      logInfo m!"{proj}"
      if let some msg ← compareWithSynthesized proj then
        if firstMsg.isNone then
          firstMsg := some msg
        else
          later := later.push proj
    firstMsg.mapM fun msg ↦ do
      let mut msg := msg
      if !later.isEmpty then
        msg := m!"{msg}\nSimilarly for {later}"
      addMessageContext msg

namespace Batteries.Tactic.Lint

@[env_linter] def instanceDiamonds : Lint.Linter where
  noErrorsFound := "No problem"
  errorsFound := "Some problems"
  test := fun declName => do
    if declName.isInternal then return none
    findDiamonds declName

end Batteries.Tactic.Lint
